name: Gravitee.io
description: Gravitee.io - Open Source API Management Solution
version: lastest
category: API Managment
licence : Apache Licence, version 2
maintainer: sebastien.renno@leansys.fr
projectURL: https://gravitee.io